//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public Delivery()
        {
            this.Delivery_Menu = new HashSet<Delivery_Menu>();
        }
    
        public int delivery_id { get; set; }
        public int user_web_id { get; set; }
        public string cod_pago { get; set; }
        public string direccion_delivery { get; set; }
        public System.DateTime fecha_delivery { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<Delivery_Menu> Delivery_Menu { get; set; }
        public virtual Usuario_Web Usuario_Web { get; set; }
    }
}
