//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public Mesa()
        {
            this.Usuario_Mesa_Menu = new HashSet<Usuario_Mesa_Menu>();
        }
    
        public int mesa_id { get; set; }
        public int restaurant_id { get; set; }
        public Nullable<System.TimeSpan> hora_desocupada { get; set; }
        public decimal tiempo_estimado_mesa_desocupada { get; set; }
        public int stock_personas { get; set; }
        public string img_mesa { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<Usuario_Mesa_Menu> Usuario_Mesa_Menu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
