//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_gcd_reservaEntities : DbContext
    {
        public db_gcd_reservaEntities()
            : base("name=db_gcd_reservaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<Delivery_Menu> Delivery_Menu { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Plato> Plato { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
        public virtual DbSet<Restaurant_Telefono> Restaurant_Telefono { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Tipo_Plato> Tipo_Plato { get; set; }
        public virtual DbSet<User_admin> User_admin { get; set; }
        public virtual DbSet<Usuario_Mesa_Menu> Usuario_Mesa_Menu { get; set; }
        public virtual DbSet<Usuario_Web> Usuario_Web { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
