//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato
    {
        public Plato()
        {
            this.Delivery_Menu = new HashSet<Delivery_Menu>();
            this.Usuario_Mesa_Menu = new HashSet<Usuario_Mesa_Menu>();
        }
    
        public int menu_id { get; set; }
        public string nombre_menu { get; set; }
        public decimal precio { get; set; }
        public int restaurant_id { get; set; }
        public int tipo_menu_id { get; set; }
    
        public virtual ICollection<Delivery_Menu> Delivery_Menu { get; set; }
        public virtual ICollection<Usuario_Mesa_Menu> Usuario_Mesa_Menu { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Tipo_Plato Tipo_Plato { get; set; }
    }
}
