//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public Reservacion()
        {
            this.Usuario_Mesa_Menu = new HashSet<Usuario_Mesa_Menu>();
        }
    
        public int reservacion_id { get; set; }
        public int user_web_id { get; set; }
        public System.DateTime fecha_registrada { get; set; }
        public string cod_pago { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<Usuario_Mesa_Menu> Usuario_Mesa_Menu { get; set; }
        public virtual Usuario_Web Usuario_Web { get; set; }
    }
}
