//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Mesa = new HashSet<Mesa>();
            this.Plato = new HashSet<Plato>();
            this.User_admin = new HashSet<User_admin>();
            this.Restaurant_Telefono = new HashSet<Restaurant_Telefono>();
        }
    
        public int restaurant_id { get; set; }
        public string loc_latitud { get; set; }
        public string loc_longitud { get; set; }
        public string comercial_name { get; set; }
        public string legal_name { get; set; }
        public string ruc { get; set; }
        public string description { get; set; }
        public int radio { get; set; }
        public System.TimeSpan inferior_horario_atencion { get; set; }
        public System.TimeSpan superior_horario_atencion { get; set; }
        public string logo { get; set; }
    
        public virtual ICollection<Mesa> Mesa { get; set; }
        public virtual ICollection<Plato> Plato { get; set; }
        public virtual ICollection<User_admin> User_admin { get; set; }
        public virtual ICollection<Restaurant_Telefono> Restaurant_Telefono { get; set; }
    }
}
