//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_admin
    {
        public int usuario_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public int restaurant_id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
