//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Web
    {
        public Usuario_Web()
        {
            this.Delivery = new HashSet<Delivery>();
            this.Reservacion = new HashSet<Reservacion>();
        }
    
        public int user_web_id { get; set; }
        public string nombre { get; set; }
        public string apellido_materno { get; set; }
        public string apellido_paterno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string direccion { get; set; }
        public string numero_documento { get; set; }
        public string user_web_name { get; set; }
        public string password { get; set; }
        public int tipo_documento_id { get; set; }
    
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual ICollection<Reservacion> Reservacion { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
    }
}
